ALTER TABLE "JournalEntry"
ADD COLUMN "summary" TEXT,
ADD COLUMN "topics" JSONB,
ADD COLUMN "people" JSONB,
ADD COLUMN "projects" JSONB,
ADD COLUMN "emotions" JSONB,
ADD COLUMN "actionItems" JSONB,
ADD COLUMN "embedding" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[];
